### ISSUE TITLE
Configuration UI

### ISSUE THREAD

**Issue by piroor** [myokoym/auto-confirm#1]
Currently this addon has no configuration UI. It should be implemented. My idea is:
- The configuration window has a list of registered rules.
- When double-click an item, a child window appears to configure details of the rule.
  - The child window should have "text", "title", "url" (for "general" type rule), and "actions".
  - A new rule can be added via same UI.

**Comment by myokoym** [comment]
Configuration UI  has added by #3. Thank you.
